### ISSUE TITLE
Taskfile

### ISSUE THREAD

**Issue by yamd1** [yamd1/TIL#94]
taskfileでは`cmds`の中に `-`でコマンドを一行ずつ記述すると、途中で失敗した場合、Pipefileと同じように以降の行は実行されない

```yaml
tasks:
  clean:
    cmds:
      - echo "foo"
      - echo "fuga"
```
